language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install gcc python-dev python3-dev libsdl2-dev libffi-dev libegl1-mesa-dev libgles2-mesa-dev -y
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov
script:
  - pytest --cov=./
after_script:
  - codecov
notifications:
  email: false
